version: "3.8"
services:
  mypostgres:
    container_name: mypostgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: leonphoenix21
      POSTGRES_PASSWORD: vtlt123@dck
      POSTGRES_DB: student_grades
    ports:
      - "5433:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_DEFAULT_SERVER: postgres_container
    ports:
      - "5050:80"
